# 应用服务器
server:
  tomcat:
    uri-encoding: UTF-8
  port: 30001
  # 全局设置请求路径增加前缀
  servlet:
    context-path: /system


spring:
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB        # 设置单个文件最大大小为10MB
      max-request-size: 100MB    # 设置多个文件大小为100MB
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/springlearning?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称
  #  redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 15

# mybatis-plus配置 用于打印框架生成的sql语句，便于调试
mybatis-plus:
  global-config:
    db-config:
      #      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(配置后可以忽略不配置步骤二)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# minio配置
minio:
  endpoint: http://localhost:9005
  access-key: Uvvo9CqHZX07vyojSta2
  secret-key: foLfnZbikox87YvmzwSM0AgFb2Y3tZfuCos7mfOu
  bucket-name: house

# swagger配置
springdoc:
  default-flat-param-object: true

#---
#spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8

# 拦截器应路径配置
system:
  auth:
    path-patterns:
      include: /system/**
      exclude: /system/login/**,

